### ISSUE TITLE
感恩您的工作，关于收录的问题想请教

### ISSUE THREAD

**Issue by nCovCover** [jiayiliujiayi/2020nCov_individual_archives#10]
您的工作非常有价值，想请问您是如何及时地收录到这些记录的呢？如果是按话题收录会不会有遗漏的内容呢（比如有些广播并未加话题）？如果需要人工跟进您会需要网友的帮助吗？尤其是因为今天开始所谓的“生态治理”，十分担心平台对这些内容的审核会变得更严格，可能会越来越快地屏蔽……对此有一些焦虑，还望您不吝赐教，希望没有打扰到您

**Comment by jiayiliujiayi** [comment]
> 您的工作非常有价值，想请问您是如何及时地收录到这些记录的呢？如果是按话题收录会不会有遗漏的内容呢（比如有些广播并未加话题）？如果需要人工跟进您会需要网友的帮助吗？尤其是因为今天开始所谓的“生态治理”，十分担心平台对这些内容的审核会变得更严格，可能会越来越快地屏蔽……对此有一些焦虑，还望您不吝赐教，希望没有打扰到您

Hi @nCovCover ,   

谢谢您的issue。  
  
收录内容大多来自于豆瓣友邻们的转发，以及友邻们的友邻们的转发。

这个项目暂时只有我一个人在维护，所以收录的内容和时间覆盖得并不全面，遗漏肯定是有的，甚至部分些内容还来不及收录就被删除了，非常惭愧。  
  
跟进的任务也是我在做，如果有网友能帮助那当然是太好了！  

您提到的有关于内容审核的顾虑，我当然有相同的担忧。可是现下个人力量有限，唯一能做的大概只有及时跟进吧。  

谢谢！欢迎更多意见和建议哈:)

祝好， 
Jiayi

**Comment by nCovCover** [comment]
Hi Jiayi，
请您务必不要惭愧，内容被删除不是您的错。如果我给您传递了这样的感觉，十分抱歉。

我昨晚想着如何跟进一些用户的微博，发现了这样一个把讯息转化为 RSS 的工具 https://docs.rsshub.app/social-media.html#dou-ban 。微博的反爬虫算是比较严格了，这个工具里也有标注，所以我最终使用了 https://rssfeed.today 。豆瓣广播和话题的反爬似乎不那么严格？我没有尝试，不知道可用性如何。在这里推荐给您，可以做一个参照。

再次感谢您的工作！您的工作非常重要，也请不要感到有太大压力，您已经做了太多太多了。

祝好。

**Comment by jiayiliujiayi** [comment]
> Hi Jiayi，
> 请您务必不要惭愧，内容被删除不是您的错。如果我给您传递了这样的感觉，十分抱歉。
> 
> 我昨晚想着如何跟进一些用户的微博，发现了这样一个把讯息转化为 RSS 的工具 https://docs.rsshub.app/social-media.html#dou-ban 。微博的反爬虫算是比较严格了，这个工具里也有标注，所以我最终使用了 https://rssfeed.today 。豆瓣广播和话题的反爬似乎不那么严格？我没有尝试，不知道可用性如何。在这里推荐给您，可以做一个参照。
> 
> 再次感谢您的工作！您的工作非常重要，也请不要感到有太大压力，您已经做了太多太多了。
> 
> 祝好。

Hi @nCovCover ,  

谢谢您提供的链接！（写代码苦手准备从零学起 嘿嘿）  https://rssfeed.today 在我这儿边显示404，不知道是什么原因...

也非常感谢您的工作！  

祝一切顺利，
Jiayi

**Comment by nCovCover** [comment]
Hi Jiayi，

抱歉没检查那个链接，这个链接是可用的 https://rssfeed.today/weibo/

我没有做什么啦，我也不懂这些😂在我看来您的项目已经非常优秀了👍

祝一切顺利。

**Comment by jiayiliujiayi** [comment]
> Hi Jiayi，
> 
> 抱歉没检查那个链接，这个链接是可用的 https://rssfeed.today/weibo/
> 
> 我没有做什么啦，我也不懂这些😂在我看来您的项目已经非常优秀了👍
> 
> 祝一切顺利。

Hi @nCovCover ,    

非常感谢！  

祝好，  
Jiayi
