### ISSUE TITLE
关于文件梳理的几个建议

### ISSUE THREAD

**Issue by WeileiZeng** [jiayiliujiayi/2020nCov_individual_archives#11]
感谢您的收录工作。

几个建议：

1. 添加 data/ 文件夹，将md文件置于其中。这样github站点会更清晰。
2. 主目录，添加readme文件。增加（项目简介，任务看板，等内容）。类似于您网站主页上的内容。
3. 在网站 https://2020ncov-individual-archives.netlify.com/ 上添加github的链接

**Comment by WeileiZeng** [comment]
https://github.com/WeileiZeng/2020nCov_individual_archives/tree/master/scrape_scripts/py

我在repo中没看到整理好的表格数据，于是整理了一下，还不是很清爽。不知道大家有没有这方面的需求。目前接受数据定制，包括csv，yaml，json等。

**Comment by jiayiliujiayi** [comment]
> https://github.com/WeileiZeng/2020nCov_individual_archives/tree/master/scrape_scripts/py
> 
> 我在repo中没看到整理好的表格数据，于是整理了一下，还不是很清爽。不知道大家有没有这方面的需求。目前接受数据定制，包括csv，yaml，json等。

非常感谢，我来试一试哈！

**Comment by jiayiliujiayi** [comment]
> 感谢您的收录工作。
> 
> 几个建议：
> 
> 1. 添加 data/ 文件夹，将md文件置于其中。这样github站点会更清晰。
> 2. 主目录，添加readme文件。增加（项目简介，任务看板，等内容）。类似于您网站主页上的内容。
> 3. 在网站 https://2020ncov-individual-archives.netlify.com/ 上添加github的链接

继续感谢！欢迎pr哈～

**Comment by WeileiZeng** [comment]
我整理一下再发pr。你可以先更新，这样我也可以跟新一下对应目录。我的文件都放在单独的文件夹py/里，不会有冲突的。

另外请问
-- 向 阳的广播 .md	
-- 小样麻麻的广播 .md
这两个的文件名有点奇怪，可以改成和其他一样的格式吗？会导致程序出现bug

**Comment by jiayiliujiayi** [comment]
> 我整理一下再发pr。你可以先更新，这样我也可以跟新一下对应目录。我的文件都放在单独的文件夹py/里，不会有冲突的。
> 
> 另外请问
> -- 向 阳的广播 .md
> -- 小样麻麻的广播 .md
> 这两个的文件名有点奇怪，可以改成和其他一样的格式吗？会导致程序出现bug

已更新～等pr，谢谢！

Jiayi

**Comment by WeileiZeng** [comment]
已发pr
