### ISSUE TITLE
文章信息提取与处理

### ISSUE THREAD

**Issue by WeileiZeng** [jiayiliujiayi/2020nCov_individual_archives#14]
根据你的体例规范，用yaml或者json来管理是比较方便的。Github Pages可以直接提取这些信息。我做了一个demo。

https://weileizeng.github.io/2020nCov_individual_archives/

**Comment by WeileiZeng** [comment]
a reproduced post

https://weileizeng.github.io/2020nCov_individual_archives/samplepost

**Comment by jiayiliujiayi** [comment]
Hi @WeileiZeng , 

 谢谢issue，你太棒啦！  

我对于yaml和jason都不是很熟悉，所以……欢迎pr！  

Best, 
Jiayi
