### ISSUE TITLE
Android studio: signingConfig.name must not be null

### ISSUE THREAD

**Issue by infracontrolAndroidstudio** [jiayiliujiayi/2020nCov_individual_archives#15]
Hello! 
I get the following error when I press the "Sync project with gradle files" after I updated Android studio to version 3.6.1: 
java.lang.IllegalStateException; signingConfig.name must not be null . 

It works If I change  this row: 
        classpath 'com.android.tools.build:gradle:3.6.1' 
to  
        classpath 'com.android.tools.build:gradle:3.5.3'

![image](https://user-images.githubusercontent.com/61787865/75967757-95ee8e80-5ecc-11ea-8774-53b8e1a6e780.png)

![image](https://user-images.githubusercontent.com/61787865/75969273-fed70600-5ece-11ea-8964-538f28cbc38a.png)

I found the following here, but the fix did not work:
https://stackoverflow.com/questions/60390279/android-gradle-signingconfig-name-must-not-be-null 

Does anyone have any idea of a solution to the problem? 

Best Regards

Tommy

**Comment by adsfinder500** [comment]
signing.Config.name see if there is a space there somewhere that perhaps may not belong there 😃 hugs

**Comment by WeileiZeng** [comment]
building an android app?

**Comment by adsfinder500** [comment]
I might be right now I'm looking for an investor

Can you invest a couple of thousand dollars per month?

Be nice to people


Click. =)


https://docs.google.com/document/d/19fXUIIsnZQfO16_e9oXXw0e5b7Qnzpsp3BOtIt_FU7s/edit?usp=drivesdk

**Comment by jiayiliujiayi** [comment]
Hi @adsfinder500 ,  

Thank you so much for your help to develop the app.  The maintainers of this repository are all volunteers and we currently do not have any budgets.  Sorry about that!   

Let me know if you have further questions.  

Best, 
Jiayi
