### ISSUE TITLE
您的项目已录入 OpenSourceWuhan 武汉开源

### ISSUE THREAD

**Issue by WeileiZeng** [jiayiliujiayi/2020nCov_individual_archives#2]
您好！

感谢您对武汉和开源社区的贡献，您的项目已录入 OpenSourceWuhan 武汉开源,如有疑问请open an issue

武汉开源 OpenSourceWuhan 集齐了开源平台上支援武汉的项目，是一个连结各个开源项目的入口。

站点： https://weileizeng.github.io/OpenSourceWuhan/

**Comment by jiayiliujiayi** [comment]
> 您好！
> 
> 感谢您对武汉和开源社区的贡献，您的项目已录入 OpenSourceWuhan 武汉开源,如有疑问请open an issue
> 
> 武汉开源 OpenSourceWuhan 集齐了开源平台上支援武汉的项目，是一个连结各个开源项目的入口。
> 
> 站点： https://weileizeng.github.io/OpenSourceWuhan/

Hi @WeileiZeng ！   

非常感谢，已友链：）

祝好， 
Jiayi
