### ISSUE TITLE
。

### ISSUE THREAD

**Issue by ghost** [jiayiliujiayi/2020nCov_individual_archives#4]
。

**Comment by jiayiliujiayi** [comment]
> [项目绍介](https://github.com/Pratitya/wuhan2020-timeline/blob/master/README.md)
> 
> [项目内容](https://github.com/Pratitya/wuhan2020-timeline/blob/master/%E6%97%B6%E9%97%B4%E7%BA%BFTIMELINE.md)

Hi @Pratitya ，   

谢谢联系，已友链。  

祝好，
Jiayi
