### ISSUE TITLE
所有文章都是md，可以使用hexo做成静态网站

### ISSUE THREAD

**Issue by timbby** [jiayiliujiayi/2020nCov_individual_archives#6]
可以用hexo做成一个静态网站，https://hexo.io/zh-cn/
可以用https://typora.io/ 做编辑，图片可以自动保存到指定目录

**Comment by dmcyer** [comment]
chrome保存网页为单个文件(mht格式)-百度经验
https://jingyan.baidu.com/article/20b68a8852f81f796dec6266.html

**Comment by jiayiliujiayi** [comment]
> 可以用hexo做成一个静态网站，https://hexo.io/zh-cn/
> 可以用https://typora.io/ 做编辑，图片可以自动保存到指定目录

Hi @timbby ,  

谢谢建议！[网站](https://2020ncov-individual-archives.netlify.com)部署中：  
https://github.com/jiayiliujiayi/2020nCov_individual_archives.web  

希望能早日merge进来：）  

祝好，
Jiayi

**Comment by liwenliang26** [comment]
辛苦哦，一起加油！

**Comment by LyuanGH** [comment]
国人路过，一起加油！
