### ISSUE TITLE
豆瓣用户☂️的疫区记录

### ISSUE THREAD

**Issue by nCovCover** [jiayiliujiayi/2020nCov_individual_archives#7]
这份记录在微博、豆瓣小组都引起了很大的回响
https://www.douban.com/people/64903057/statuses

另外，看到豆瓣有话题 #和新冠肺炎疫情有关的记忆 https://www.douban.com/gallery/topic/125548/
供您参考

您的工作非常重要，辛苦了

**Comment by jiayiliujiayi** [comment]
> 这份记录在微博、豆瓣小组都引起了很大的回响
> https://www.douban.com/people/64903057/statuses
> 
> 另外，看到豆瓣有话题 #和新冠肺炎疫情有关的记忆 https://www.douban.com/gallery/topic/125548/
> 供您参考
> 
> 您的工作非常重要，辛苦了

Hi @nCovCover ,  

谢谢issue，谢谢提供内容来源！  

已添加，会持续关注话题：）

祝好，
Jiayi
