### ISSUE TITLE
命名方式

### ISSUE THREAD

**Issue by predb** [jiayiliujiayi/2020nCov_individual_archives#9]
豆瓣数字 ID 和域名都是固定的，而昵称随便更改；此刻保存下来的广播依照昵称来命名，下一刻友邻变更了昵称，后面看到的人就不好查找了吧。

比如
[https://www.douban.com/people/cclethe/statuses](url)

**Comment by jiayiliujiayi** [comment]
Hi @aimutu ,  

来函敬悉:)  

豆瓣ID已在.md正文内有所记录，例如：https://raw.githubusercontent.com/jiayiliujiayi/2020nCov_individual_archives/master/01-20-Lawyer_Tam-%E5%A4%A7%E5%AF%92.md  中第二行所示。  

谢谢，
Jiayi
